# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bind_list <- function(L, n_col, col_classes) {
    .Call('ncbi_bind_list', PACKAGE = 'ncbi', L, n_col, col_classes)
}

index_gi_taxid <- function(nucfile, protfile, outfile) {
    invisible(.Call('ncbi_index_gi_taxid', PACKAGE = 'ncbi', nucfile, protfile, outfile))
}

merge_gi_taxid <- function(nucfile, protfile, outfile) {
    invisible(.Call('ncbi_merge_gi_taxid', PACKAGE = 'ncbi', nucfile, protfile, outfile))
}

readNodes <- function(filename) {
    .Call('ncbi_readNodes', PACKAGE = 'ncbi', filename)
}

readNames <- function(filename) {
    .Call('ncbi_readNames', PACKAGE = 'ncbi', filename)
}

readMerged <- function(filename) {
    .Call('ncbi_readMerged', PACKAGE = 'ncbi', filename)
}

